### ISSUE TITLE
pass telegram api version to image label

### ISSUE THREAD

**Issue by centralhardware** [lukaszraczylo/tdlib-telegram-bot-api-docker#1]

**Comment by lukaszraczylo** [comment]
@centralhardware Just to clarify and confirm before any work will be done - did you requested docker _tag_ or docker image _label_ ? :)

**Comment by centralhardware** [comment]
I would like to be able to make sure that the running image is with the latest version of the api, I have not found a way to see the version of the api either through CLI or through HTTP. I fount the version only in CMakeLists.txt (https://github.com/tdlib/telegram-bot-api/blob/202ddaffabcff16523dba672a27b35c92a050338/CMakeLists.txt#L3). 
I think about image label but the tag, it seems to me, is absolutely the same applicable

**Comment by lukaszraczylo** [comment]
Sorry for delay - I've added new tag ( for example `api-5.1` ) as per commit 8dd85a6 :) Enjoy!
